baseurl = "/"
languageCode = "en-us"
title = "A Hugo website"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    pre = ""
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/rstudio/blogdown"
    pre = "fa-facebook-square"
    weight = 3
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/rstudio"
    pre = "fa-twitter-square"
    weight = 2
[[menu.main]]
    name = "Posts"
    url = "/post/"
    pre = "fa-twitter-square"
    weight = 2
    
[params]
    description = "A website built through Hugo and blogdown."
    customCSS = ["css/erum.css", "css/fontawesome.min.css"]
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"
    
    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "eRum2020.png"
    width = 50
    height = 50
    alt = "Logo"
